services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ContaoEstateManager\EstateManager\:
        resource: '../../'
        exclude: '../../{Model,DependencyInjection,Resources}'
