services:
    _defaults:
        autowire: true

    ContaoEstateManager\EstateManager\Controller\EstateManagerController:
        arguments:
            - '@contao.framework'
        tags:
            - controller.service_arguments
